/* Generates supabase/seed/catalogue.sql from data/products.json (a byte-identical copy of dist/store/products.json).
   Nothing here connects anywhere; it only writes SQL. Safe to re-run: existing rows (and any admin edits to price or
   stock) are never overwritten. Also writes supabase/setup-all.sql (migrations + seed) for pasting into the SQL Editor.
   Usage: node scripts/generate-seed.mjs */
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const data = JSON.parse(fs.readFileSync(path.join(ROOT, 'data/products.json'), 'utf8'));
const STOCK_PER_SIZE = 10; // prototype demo stock, flagged stock_source = 'prototype'

const q = v => v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`;
const arr = a => `array[${(a || []).map(q).join(', ')}]::text[]`;
const json = o => `${q(JSON.stringify(o ?? {}))}::jsonb`;
const imagePath = p => `products/${p.id}.webp`;

const out = [];
out.push(`-- GENERATED by scripts/generate-seed.mjs from data/products.json on ${new Date().toISOString().slice(0, 10)}. Do not edit by hand.`);
out.push(`-- ${data.products.length} products, ${data.products.reduce((n, p) => n + p.variants.length, 0)} variants (${STOCK_PER_SIZE} prototype units each), ${data.categories.length} categories.`);
out.push('begin;', '');

out.push('-- categories (parents first)');
const cats = [...data.categories.filter(c => !c.parent), ...data.categories.filter(c => c.parent)];
for (const [i, c] of cats.entries()) {
  out.push(`insert into public.categories (id, label, parent_id, sort_order) values (${q(c.id)}, ${q(c.label)}, ${q(c.parent)}, ${i}) on conflict (id) do update set label = excluded.label, parent_id = excluded.parent_id, sort_order = excluded.sort_order;`);
}

out.push('', '-- products');
for (const p of data.products) {
  out.push(`insert into public.products (id, sku, slug, name, description, category_id, subcategory_id, price_paise, colour_label, colour_swatch, features, is_featured, status, data_status, catalogue_ref, material, care, origin, review) values (` +
    [q(p.id), q(p.sku), q(p.slug), q(p.name), q(p.description), q(p.category), q(p.subcategory), Math.round(p.price * 100), q(p.colour?.label), q(p.colour?.swatches?.[0]),
     arr(p.features), p.featured ? 'true' : 'false', q('active'), q(p.dataStatus || 'prototype'), q(p.catalogueRef), q(p.material), q(p.care), q(p.origin), json(p.review)].join(', ') +
    `) on conflict (id) do nothing;`);
}

out.push('', `-- size variants: ${STOCK_PER_SIZE} units of PROTOTYPE stock per size, plus a 'seed' inventory movement for each new variant`);
for (const p of data.products) {
  const rows = p.variants.map((v, i) => `(${q(p.id)}, ${q(v.size)}, ${q(`${p.sku}-${v.size}`)}, ${i}, ${v.available ? STOCK_PER_SIZE : 0}, 'prototype', ${v.available ? 'true' : 'false'})`).join(',\n    ');
  out.push(`with new_variants as (
  insert into public.product_variants (product_id, size, sku, sort_order, stock_qty, stock_source, is_active) values
    ${rows}
  on conflict (product_id, size) do nothing
  returning id, stock_qty
) insert into public.inventory_movements (variant_id, delta, reason, note)
  select id, stock_qty, 'seed', 'Prototype demo stock' from new_variants;`);
}

out.push('', '-- primary images (files are uploaded to the product-images bucket by scripts/upload-images.mjs)');
for (const p of data.products) {
  const m = p.media?.primary;
  if (!m || p.media.status === 'held') { out.push(`-- ${p.sku}: no image (held)`); continue; }
  out.push(`insert into public.product_images (product_id, storage_path, width, height, alt, quality, zoom, is_primary, sort_order) values (${q(p.id)}, ${q(imagePath(p))}, ${m.width}, ${m.height}, ${q(m.alt)}, ${q(m.quality === 'official' ? 'official' : 'prototype')}, ${m.zoom ? 'true' : 'false'}, true, 0) on conflict (product_id, storage_path) do nothing;`);
}

out.push('', '-- collections (New Arrivals keeps its order)');
for (const c of data.collections) {
  out.push(`insert into public.collections (id, label, data_status, note) values (${q(c.id)}, ${q(c.label)}, ${q(c.dataStatus)}, ${q(c.note)}) on conflict (id) do update set label = excluded.label, data_status = excluded.data_status, note = excluded.note;`);
  c.productIds.forEach((id, i) => out.push(`insert into public.collection_products (collection_id, product_id, position) values (${q(c.id)}, ${q(id)}, ${i + 1}) on conflict (collection_id, product_id) do nothing;`));
}

out.push('', '-- styled-with pairings (as paired in the prototype catalogue)');
for (const p of data.products) (p.styledWith || []).forEach((id, i) => out.push(`insert into public.product_relations (product_id, related_id, kind, position) values (${q(p.id)}, ${q(id)}, 'styled_with', ${i}) on conflict do nothing;`));

out.push('', 'commit;', '');
fs.mkdirSync(path.join(ROOT, 'supabase/seed'), {recursive: true});
fs.writeFileSync(path.join(ROOT, 'supabase/seed/catalogue.sql'), out.join('\n'));

// One file for the Supabase SQL Editor: all migrations in order, then the seed.
const migDir = path.join(ROOT, 'supabase/migrations');
const migrations = fs.readdirSync(migDir).filter(f => f.endsWith('.sql')).sort();
const all = ['-- KITSYUU: full database setup (all migrations + catalogue seed). For a FRESH project only.',
  '-- Paste into Supabase Dashboard -> SQL Editor -> Run. Generated by scripts/generate-seed.mjs.', '',
  ...migrations.flatMap(f => [`-- ===== ${f} =====`, fs.readFileSync(path.join(migDir, f), 'utf8'), '']),
  '-- ===== seed/catalogue.sql =====', out.join('\n')];
fs.writeFileSync(path.join(ROOT, 'supabase/setup-all.sql'), all.join('\n'));
console.log(`catalogue.sql: ${data.products.length} products, ${data.products.reduce((n, p) => n + p.variants.length, 0)} variants, ${data.products.filter(p => p.media?.primary).length} images, ${data.categories.length} categories`);
console.log(`setup-all.sql: ${migrations.length} migrations + seed`);
