/* Object storage for product images, behind a small interface so the business logic does not depend on a provider.
   - supabaseStorage: the existing public 'product-images' bucket through the Storage REST API, using a server-only
     service key (never sent to the browser).
   - localStorage: a folder on disk, for local development and automated tests (never touches the live bucket). */
import fs from 'node:fs/promises';
import path from 'node:path';

export interface ObjectStorage {
  readonly kind: 'supabase' | 'local';
  put(objectPath: string, body: Buffer, contentType: string): Promise<void>;
  remove(objectPath: string): Promise<void>;
}

/** Object paths are generated by the server; still, refuse anything that is not a plain relative path. */
export function assertObjectPath(p: string) {
  if (!/^[a-z0-9][a-z0-9/_.-]{0,200}$/.test(p) || p.includes('..') || p.includes('//')) throw new Error(`Invalid storage path: ${p}`);
}

export function supabaseStorage({ url, serviceKey, bucket }: { url: string; serviceKey: string; bucket: string }): ObjectStorage {
  const base = `${url.replace(/\/+$/, '')}/storage/v1/object`;
  const headers = { Authorization: `Bearer ${serviceKey}`, apikey: serviceKey };
  return {
    kind: 'supabase',
    async put(objectPath, body, contentType) {
      assertObjectPath(objectPath);
      const r = await fetch(`${base}/${bucket}/${objectPath}`, {
        method: 'POST', headers: { ...headers, 'Content-Type': contentType, 'Cache-Control': '31536000', 'x-upsert': 'false' }, body: new Uint8Array(body),
      });
      if (!r.ok) throw new Error(`Storage upload failed (HTTP ${r.status})`);
    },
    async remove(objectPath) {
      assertObjectPath(objectPath);
      const r = await fetch(`${base}/${bucket}`, { method: 'DELETE', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify({ prefixes: [objectPath] }) });
      if (!r.ok) throw new Error(`Storage delete failed (HTTP ${r.status})`);
    },
  };
}

export function localStorage(root: string): ObjectStorage {
  const resolve = (p: string) => {
    assertObjectPath(p);
    const full = path.resolve(root, p);
    if (!full.startsWith(path.resolve(root) + path.sep)) throw new Error(`Invalid storage path: ${p}`);
    return full;
  };
  return {
    kind: 'local',
    async put(objectPath, body) {
      const full = resolve(objectPath);
      await fs.mkdir(path.dirname(full), { recursive: true });
      await fs.writeFile(full, body, { flag: 'wx' });                 // never overwrite an existing object
    },
    async remove(objectPath) { await fs.rm(resolve(objectPath), { force: true }); },
  };
}
