-- KITSYUU: full database setup (all migrations + catalogue seed). For a FRESH project only.
-- Paste into Supabase Dashboard -> SQL Editor -> Run. Generated by scripts/generate-seed.mjs.

-- ===== 20260925000100_schema.sql =====
-- KITSYUU store: core schema (Phase 4.2)
-- Money is integer paise. Product ids keep the existing catalogue ids (ky-proto-001 …) so they match
-- the storefront, cart and wishlist data exactly. New products get a generated kts-xxxxxxxx id.

-- ---------- enums ----------
create type public.app_role as enum ('customer', 'admin');
create type public.product_status as enum ('active', 'draft', 'archived');
create type public.order_status as enum ('pending_payment', 'paid', 'processing', 'shipped', 'delivered', 'cancelled', 'payment_failed', 'refunded');

-- ---------- helpers ----------
create or replace function public.set_updated_at() returns trigger
language plpgsql set search_path = '' as $$
begin new.updated_at = now(); return new; end $$;

-- ---------- catalogue ----------
create table public.categories (
  id          text primary key,                              -- 'tops', 'tops.hoodies'
  label       text not null,
  parent_id   text references public.categories (id) on delete restrict,
  sort_order  int  not null default 0,
  created_at  timestamptz not null default now()
);

create table public.products (
  id             text primary key default ('kts-' || substr(replace(gen_random_uuid()::text, '-', ''), 1, 8)),
  sku            text not null unique,
  slug           text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  name           text not null,
  description    text not null default '',
  category_id    text not null references public.categories (id),
  subcategory_id text references public.categories (id),
  price_paise    integer not null check (price_paise >= 0),
  colour_label   text,
  colour_swatch  text,
  features       text[] not null default '{}',
  is_featured    boolean not null default false,
  status         public.product_status not null default 'active',
  data_status    text not null default 'prototype' check (data_status in ('prototype', 'official')),
  catalogue_ref  text,
  material       text,
  care           text,
  origin         text,
  review         jsonb not null default '{}'::jsonb,           -- image-rights review flags from the catalogue
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create index products_category_idx on public.products (category_id);
create index products_subcategory_idx on public.products (subcategory_id);
create trigger products_updated_at before update on public.products for each row execute function public.set_updated_at();

create table public.product_variants (
  id           uuid primary key default gen_random_uuid(),
  product_id   text not null references public.products (id) on delete cascade,
  size         text not null,
  sku          text not null unique,                          -- product sku + '-' + size
  sort_order   int  not null default 0,
  price_paise  integer check (price_paise >= 0),              -- null = use the product price
  stock_qty    integer not null default 0 check (stock_qty >= 0),
  stock_source text not null default 'manual' check (stock_source in ('prototype', 'manual', 'official')),
  is_active    boolean not null default true,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  unique (product_id, size)
);
comment on column public.product_variants.stock_source is 'prototype = demo stock seeded for development (10 per size), not real inventory';
create trigger product_variants_updated_at before update on public.product_variants for each row execute function public.set_updated_at();

create table public.product_images (
  id           uuid primary key default gen_random_uuid(),
  product_id   text not null references public.products (id) on delete cascade,
  storage_path text not null,                                 -- path inside the product-images bucket
  width        int,
  height       int,
  alt          text not null default '',
  quality      text not null default 'prototype' check (quality in ('prototype', 'official')),
  zoom         boolean not null default false,
  is_primary   boolean not null default false,
  sort_order   int not null default 0,
  created_at   timestamptz not null default now(),
  unique (product_id, storage_path)
);
create unique index product_images_one_primary on public.product_images (product_id) where is_primary;

create table public.collections (
  id          text primary key,                               -- 'new-arrivals'
  label       text not null,
  data_status text not null default 'prototype',
  note        text
);
create table public.collection_products (
  collection_id text not null references public.collections (id) on delete cascade,
  product_id    text not null references public.products (id) on delete cascade,
  position      int  not null,
  primary key (collection_id, product_id)
);

create table public.product_relations (
  product_id text not null references public.products (id) on delete cascade,
  related_id text not null references public.products (id) on delete cascade,
  kind       text not null default 'styled_with' check (kind in ('styled_with')),
  position   int  not null default 0,
  primary key (product_id, related_id, kind)
);

-- ---------- customers ----------
create table public.profiles (
  id         uuid primary key references auth.users (id) on delete cascade,
  email      text,
  full_name  text,
  phone      text,
  role       public.app_role not null default 'customer',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at();

create table public.addresses (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references auth.users (id) on delete cascade,
  full_name  text not null,
  phone      text not null,
  line1      text not null,
  line2      text,
  city       text not null,
  state      text not null,
  pin        text not null check (pin ~ '^[1-9][0-9]{5}$'),
  country    text not null default 'India',
  is_default boolean not null default false,
  created_at timestamptz not null default now()
);
create index addresses_user_idx on public.addresses (user_id);

create table public.cart_items (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references auth.users (id) on delete cascade,
  variant_id uuid not null references public.product_variants (id) on delete cascade,
  qty        int  not null check (qty between 1 and 10),     -- same cap as the storefront
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, variant_id)                                -- same product + size merges into one line
);
create trigger cart_items_updated_at before update on public.cart_items for each row execute function public.set_updated_at();

create table public.wishlist_items (
  user_id    uuid not null references auth.users (id) on delete cascade,
  product_id text not null references public.products (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, product_id)
);

-- ---------- orders ----------
create table public.orders (
  id                  uuid primary key default gen_random_uuid(),
  order_number        text not null unique default ('KTS-' || to_char(now() at time zone 'Asia/Kolkata', 'YYMMDD') || '-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 6))),
  user_id             uuid not null references auth.users (id) on delete restrict,
  status              public.order_status not null default 'pending_payment',
  currency            text not null default 'INR',
  subtotal_paise      integer not null check (subtotal_paise >= 0),
  total_paise         integer not null check (total_paise >= 0),   -- prices are tax-inclusive prototype prices; no GST line
  contact             jsonb not null default '{}'::jsonb,
  shipping_address    jsonb not null default '{}'::jsonb,
  razorpay_order_id   text unique,
  razorpay_payment_id text unique,
  paid_at             timestamptz,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);
create index orders_user_idx on public.orders (user_id, created_at desc);
create index orders_status_idx on public.orders (status, created_at desc);
create trigger orders_updated_at before update on public.orders for each row execute function public.set_updated_at();

create table public.order_items (
  id               uuid primary key default gen_random_uuid(),
  order_id         uuid not null references public.orders (id) on delete cascade,
  product_id       text references public.products (id) on delete set null,
  variant_id       uuid references public.product_variants (id) on delete set null,
  sku              text not null,                             -- snapshot at purchase time
  name             text not null,
  size             text not null,
  image_path       text,
  unit_price_paise integer not null check (unit_price_paise >= 0),
  qty              int not null check (qty between 1 and 10),
  line_total_paise integer not null check (line_total_paise >= 0)
);
create index order_items_order_idx on public.order_items (order_id);

create table public.order_status_history (
  id          bigint generated always as identity primary key,
  order_id    uuid not null references public.orders (id) on delete cascade,
  from_status public.order_status,
  to_status   public.order_status not null,
  changed_by  uuid references auth.users (id) on delete set null,
  note        text,
  created_at  timestamptz not null default now()
);
create index order_status_history_order_idx on public.order_status_history (order_id, created_at);

create table public.inventory_movements (
  id         bigint generated always as identity primary key,
  variant_id uuid not null references public.product_variants (id) on delete cascade,
  delta      int  not null,
  reason     text not null check (reason in ('seed', 'sale', 'restock', 'admin_adjust', 'cancel')),
  order_id   uuid references public.orders (id) on delete set null,
  created_by uuid references auth.users (id) on delete set null,
  note       text,
  created_at timestamptz not null default now()
);
create index inventory_movements_variant_idx on public.inventory_movements (variant_id, created_at desc);

create table public.payment_events (
  id           text primary key,                              -- Razorpay event id: each event is processed once
  type         text not null,
  payload      jsonb not null,
  received_at  timestamptz not null default now(),
  processed_at timestamptz
);


-- ===== 20260925000200_auth_roles_rls.sql =====
-- KITSYUU store: customer/admin roles and Row Level Security (Phase 4.2)
-- Deny by default: RLS is enabled on every table and only the policies below grant access.
-- The server (service-role key, never sent to the browser) bypasses RLS for order creation, payment
-- verification and stock changes.

-- ---------- roles ----------
-- True when the signed-in user has the admin role. SECURITY DEFINER so it can read profiles under RLS.
create or replace function public.is_admin() returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (select 1 from public.profiles where id = (select auth.uid()) and role = 'admin');
$$;
revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

-- Every new auth user gets a customer profile. Admins are promoted separately (see scripts/promote-admin.mjs).
create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, nullif(new.raw_user_meta_data ->> 'full_name', ''))
  on conflict (id) do nothing;
  return new;
end $$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

-- Customers may edit their own name and phone, never their role or email.
revoke update on public.profiles from anon, authenticated;
grant update (full_name, phone) on public.profiles to authenticated;

-- ---------- enable RLS everywhere ----------
alter table public.categories           enable row level security;
alter table public.products             enable row level security;
alter table public.product_variants     enable row level security;
alter table public.product_images       enable row level security;
alter table public.collections          enable row level security;
alter table public.collection_products  enable row level security;
alter table public.product_relations    enable row level security;
alter table public.profiles             enable row level security;
alter table public.addresses            enable row level security;
alter table public.cart_items           enable row level security;
alter table public.wishlist_items       enable row level security;
alter table public.orders               enable row level security;
alter table public.order_items          enable row level security;
alter table public.order_status_history enable row level security;
alter table public.inventory_movements  enable row level security;
alter table public.payment_events       enable row level security;

-- ---------- catalogue: public read (active only), admin write ----------
create policy "categories: public read" on public.categories for select to anon, authenticated using (true);
create policy "categories: admin write" on public.categories for all to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));

create policy "products: public read active" on public.products for select to anon, authenticated
  using (status = 'active' or (select public.is_admin()));
create policy "products: admin write" on public.products for all to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));

create policy "variants: public read" on public.product_variants for select to anon, authenticated
  using ((select public.is_admin()) or exists (select 1 from public.products p where p.id = product_id and p.status = 'active'));
create policy "variants: admin write" on public.product_variants for all to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));

create policy "images: public read" on public.product_images for select to anon, authenticated
  using ((select public.is_admin()) or exists (select 1 from public.products p where p.id = product_id and p.status = 'active'));
create policy "images: admin write" on public.product_images for all to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));

create policy "collections: public read" on public.collections for select to anon, authenticated using (true);
create policy "collections: admin write" on public.collections for all to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));
create policy "collection_products: public read" on public.collection_products for select to anon, authenticated using (true);
create policy "collection_products: admin write" on public.collection_products for all to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));
create policy "relations: public read" on public.product_relations for select to anon, authenticated using (true);
create policy "relations: admin write" on public.product_relations for all to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));

-- ---------- profiles ----------
create policy "profiles: read own or admin" on public.profiles for select to authenticated
  using (id = (select auth.uid()) or (select public.is_admin()));
create policy "profiles: update own" on public.profiles for update to authenticated
  using (id = (select auth.uid())) with check (id = (select auth.uid()));
-- (no insert/delete policies: profiles are created by the auth trigger and removed with the auth user)

-- ---------- addresses, cart, wishlist: owner only ----------
create policy "addresses: owner" on public.addresses for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy "addresses: admin read" on public.addresses for select to authenticated using ((select public.is_admin()));

create policy "cart: owner" on public.cart_items for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));

create policy "wishlist: owner" on public.wishlist_items for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));

-- ---------- orders: owner/admin read; writes only from the server (service role) ----------
create policy "orders: read own or admin" on public.orders for select to authenticated
  using (user_id = (select auth.uid()) or (select public.is_admin()));
create policy "orders: admin update" on public.orders for update to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));

create policy "order_items: read own or admin" on public.order_items for select to authenticated
  using ((select public.is_admin()) or exists (select 1 from public.orders o where o.id = order_id and o.user_id = (select auth.uid())));

create policy "status_history: read own or admin" on public.order_status_history for select to authenticated
  using ((select public.is_admin()) or exists (select 1 from public.orders o where o.id = order_id and o.user_id = (select auth.uid())));
create policy "status_history: admin insert" on public.order_status_history for insert to authenticated
  with check ((select public.is_admin()));

create policy "inventory: admin read" on public.inventory_movements for select to authenticated using ((select public.is_admin()));
-- payment_events: no policies at all (server only).


-- ===== 20260925000300_storage.sql =====
-- KITSYUU store: product-images Storage bucket (Phase 4.2)
-- Public bucket: images are readable by anyone through their public URL. Only admins can upload, replace or delete.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('product-images', 'product-images', true, 5242880, array['image/webp', 'image/jpeg', 'image/png'])
on conflict (id) do update
  set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

create policy "product-images: public read" on storage.objects for select to anon, authenticated
  using (bucket_id = 'product-images');
create policy "product-images: admin insert" on storage.objects for insert to authenticated
  with check (bucket_id = 'product-images' and (select public.is_admin()));
create policy "product-images: admin update" on storage.objects for update to authenticated
  using (bucket_id = 'product-images' and (select public.is_admin()))
  with check (bucket_id = 'product-images' and (select public.is_admin()));
create policy "product-images: admin delete" on storage.objects for delete to authenticated
  using (bucket_id = 'product-images' and (select public.is_admin()));


-- ===== seed/catalogue.sql =====
-- GENERATED by scripts/generate-seed.mjs from data/products.json on 2026-09-25. Do not edit by hand.
-- 22 products, 110 variants (10 prototype units each), 10 categories.
begin;

-- categories (parents first)
insert into public.categories (id, label, parent_id, sort_order) values ('tops', 'Tops', null, 0) on conflict (id) do update set label = excluded.label, parent_id = excluded.parent_id, sort_order = excluded.sort_order;
insert into public.categories (id, label, parent_id, sort_order) values ('bottoms', 'Bottoms', null, 1) on conflict (id) do update set label = excluded.label, parent_id = excluded.parent_id, sort_order = excluded.sort_order;
insert into public.categories (id, label, parent_id, sort_order) values ('outerwear', 'Outerwear', null, 2) on conflict (id) do update set label = excluded.label, parent_id = excluded.parent_id, sort_order = excluded.sort_order;
insert into public.categories (id, label, parent_id, sort_order) values ('tops.shirts', 'Shirts', 'tops', 3) on conflict (id) do update set label = excluded.label, parent_id = excluded.parent_id, sort_order = excluded.sort_order;
insert into public.categories (id, label, parent_id, sort_order) values ('tops.tops', 'Tops', 'tops', 4) on conflict (id) do update set label = excluded.label, parent_id = excluded.parent_id, sort_order = excluded.sort_order;
insert into public.categories (id, label, parent_id, sort_order) values ('tops.hoodies', 'Hoodies', 'tops', 5) on conflict (id) do update set label = excluded.label, parent_id = excluded.parent_id, sort_order = excluded.sort_order;
insert into public.categories (id, label, parent_id, sort_order) values ('bottoms.trousers', 'Trousers', 'bottoms', 6) on conflict (id) do update set label = excluded.label, parent_id = excluded.parent_id, sort_order = excluded.sort_order;
insert into public.categories (id, label, parent_id, sort_order) values ('bottoms.jeans', 'Jeans', 'bottoms', 7) on conflict (id) do update set label = excluded.label, parent_id = excluded.parent_id, sort_order = excluded.sort_order;
insert into public.categories (id, label, parent_id, sort_order) values ('bottoms.shorts-skirts', 'Shorts / Skirts', 'bottoms', 8) on conflict (id) do update set label = excluded.label, parent_id = excluded.parent_id, sort_order = excluded.sort_order;
insert into public.categories (id, label, parent_id, sort_order) values ('outerwear.jackets', 'Jackets', 'outerwear', 9) on conflict (id) do update set label = excluded.label, parent_id = excluded.parent_id, sort_order = excluded.sort_order;

-- products
insert into public.products (id, sku, slug, name, description, category_id, subcategory_id, price_paise, colour_label, colour_swatch, features, is_featured, status, data_status, catalogue_ref, material, care, origin, review) values ('ky-proto-001', 'KTS-TOP-001', 'asymmetric-zip-collar-top', 'Asymmetric Zip Collar Top', 'A statement long-sleeve top featuring an oversized asymmetric collar, zip-front construction and lace-up detailing near the hem. The washed taupe and grey visual treatment gives the piece an experimental Japanese-streetwear character.', 'tops', 'tops.tops', 249900, 'Taupe / Grey', '#7c6e5d', array['Asymmetric oversized collar', 'Front zip', 'Smudged graphic print', 'Lace-up detail at hem', 'Long sleeves']::text[], false, 'active', 'prototype', 'P2-1', null, null, null, '{"imageRights":"unconfirmed","thirdPartyMarks":false,"personVisible":false,"otherItemsInFrame":false}'::jsonb) on conflict (id) do nothing;
insert into public.products (id, sku, slug, name, description, category_id, subcategory_id, price_paise, colour_label, colour_swatch, features, is_featured, status, data_status, catalogue_ref, material, care, origin, review) values ('ky-proto-002', 'KTS-BTM-001', 'draped-utility-wide-trousers', 'Draped Utility Wide Trousers', 'Wide-leg trousers featuring a relaxed silhouette and a distinctive draped wrap-style panel around the upper leg. Designed as a statement oversized bottom for layered streetwear styling.', 'bottoms', 'bottoms.trousers', 299900, 'Khaki / Taupe', '#786b59', array['Elasticated drawstring waist', 'Draped wrap panel with tie', 'Wide leg']::text[], false, 'active', 'prototype', 'P2-2', null, null, null, '{"imageRights":"unconfirmed","thirdPartyMarks":false,"personVisible":false,"otherItemsInFrame":true}'::jsonb) on conflict (id) do nothing;
insert into public.products (id, sku, slug, name, description, category_id, subcategory_id, price_paise, colour_label, colour_swatch, features, is_featured, status, data_status, catalogue_ref, material, care, origin, review) values ('ky-proto-003', 'KTS-TOP-002', 'washed-lace-up-pointed-shirt', 'Washed Lace-Up Pointed Shirt', 'A washed blue-grey long-sleeve shirt with an elongated pointed silhouette and lace-up detailing. Pale cuffs contrast against the distressed printed body.', 'tops', 'tops.shirts', 279900, 'Washed Blue / Grey', '#899394', array['Lace-up front', 'Washed all-over print', 'Pointed hem', 'Contrast cuffs', 'Pointed collar']::text[], false, 'active', 'prototype', 'P2-3', null, null, null, '{"imageRights":"unconfirmed","thirdPartyMarks":false,"personVisible":false,"otherItemsInFrame":true}'::jsonb) on conflict (id) do nothing;
insert into public.products (id, sku, slug, name, description, category_id, subcategory_id, price_paise, colour_label, colour_swatch, features, is_featured, status, data_status, catalogue_ref, material, care, origin, review) values ('ky-proto-004', 'KTS-BTM-002', 'check-buckle-mini-skirt', 'Check Buckle Mini Skirt', 'A statement check mini skirt combining a light-blue and red checked pattern with an oversized buckle belt and asymmetrical handkerchief-style hem.', 'bottoms', 'bottoms.shorts-skirts', 229900, 'Light Blue / Red', '#b5c6d1', array['Oversized buckle belt', 'Ruffled handkerchief hem', 'Check pattern']::text[], true, 'active', 'prototype', 'P2-4', null, null, null, '{"imageRights":"unconfirmed","thirdPartyMarks":false,"personVisible":false,"otherItemsInFrame":true}'::jsonb) on conflict (id) do nothing;
insert into public.products (id, sku, slug, name, description, category_id, subcategory_id, price_paise, colour_label, colour_swatch, features, is_featured, status, data_status, catalogue_ref, material, care, origin, review) values ('ky-proto-005', 'KTS-TOP-003', 'sheer-floral-lace-up-top', 'Sheer Floral Lace-Up Top', 'A lightweight-looking sheer sleeveless top featuring floral embroidery and adjustable lace-up detailing along the sides. Designed as a layering-focused statement piece.', 'tops', 'tops.tops', 219900, 'Off White', '#babbb9', array['Sheer body', 'Floral embroidery', 'Side lace-up ties', 'Sleeveless']::text[], false, 'active', 'prototype', 'P2-5', null, null, null, '{"imageRights":"unconfirmed","thirdPartyMarks":false,"personVisible":false,"otherItemsInFrame":false}'::jsonb) on conflict (id) do nothing;
insert into public.products (id, sku, slug, name, description, category_id, subcategory_id, price_paise, colour_label, colour_swatch, features, is_featured, status, data_status, catalogue_ref, material, care, origin, review) values ('ky-proto-006', 'KTS-BTM-003', 'charcoal-pleated-balloon-trousers', 'Charcoal Pleated Balloon Trousers', 'Relaxed charcoal trousers with deep pleats and a dramatic balloon-leg silhouette. The oversized shape gives the piece a strong contemporary streetwear profile.', 'bottoms', 'bottoms.trousers', 299900, 'Charcoal / Black', '#19191f', array['Front pleats', 'Balloon leg', 'Button and zip fly', 'Belt loops']::text[], false, 'active', 'prototype', 'P2-6', null, null, null, '{"imageRights":"unconfirmed","thirdPartyMarks":false,"personVisible":false,"otherItemsInFrame":true}'::jsonb) on conflict (id) do nothing;
insert into public.products (id, sku, slug, name, description, category_id, subcategory_id, price_paise, colour_label, colour_swatch, features, is_featured, status, data_status, catalogue_ref, material, care, origin, review) values ('ky-proto-007', 'KTS-TOP-004', 'acid-wash-gothic-hooded-top', 'Acid Wash Gothic Hooded Top', 'A sleeveless hooded top featuring an acid-washed grey appearance, eyelet details and a gothic-inspired graphic across the front.', 'tops', 'tops.hoodies', 249900, 'Grey / Acid Wash', '#3f3e38', array['Acid-wash finish', 'Hood', 'Eyelet trim at armholes', 'Front graphic', 'Distressed detailing']::text[], false, 'active', 'prototype', 'P3-1', null, null, null, '{"imageRights":"unconfirmed","thirdPartyMarks":true,"personVisible":false,"otherItemsInFrame":true}'::jsonb) on conflict (id) do nothing;
insert into public.products (id, sku, slug, name, description, category_id, subcategory_id, price_paise, colour_label, colour_swatch, features, is_featured, status, data_status, catalogue_ref, material, care, origin, review) values ('ky-proto-008', 'KTS-BTM-004', 'faded-black-wide-leg-jeans', 'Faded Black Wide-Leg Jeans', 'Wide-leg black denim featuring a faded wash and visible seam detailing. The relaxed proportions create an oversized streetwear silhouette.', 'bottoms', 'bottoms.jeans', 349900, 'Faded Black', '#272729', array['Faded wash', 'Wide leg', 'Front seam lines', 'Five-pocket styling']::text[], false, 'active', 'prototype', 'P3-2', null, null, null, '{"imageRights":"unconfirmed","thirdPartyMarks":false,"personVisible":false,"otherItemsInFrame":true}'::jsonb) on conflict (id) do nothing;
insert into public.products (id, sku, slug, name, description, category_id, subcategory_id, price_paise, colour_label, colour_swatch, features, is_featured, status, data_status, catalogue_ref, material, care, origin, review) values ('ky-proto-009', 'KTS-TOP-005', 'layered-pinstripe-waffle-shirt', 'Layered Pinstripe Waffle Shirt', 'A short-sleeve black pinstripe shirt styled over a contrasting light-grey long-sleeve layer, creating a layered streetwear look with contrasting textures.', 'tops', 'tops.shirts', 279900, 'Black / Light Grey', '#252323', array['Pinstripe', 'Short sleeve over long waffle sleeve', 'Button front', 'Boxy cut']::text[], false, 'active', 'prototype', 'P3-3', null, null, null, '{"imageRights":"unconfirmed","thirdPartyMarks":true,"personVisible":false,"otherItemsInFrame":false}'::jsonb) on conflict (id) do nothing;
insert into public.products (id, sku, slug, name, description, category_id, subcategory_id, price_paise, colour_label, colour_swatch, features, is_featured, status, data_status, catalogue_ref, material, care, origin, review) values ('ky-proto-010', 'KTS-BTM-005', 'grey-pleated-drawstring-trousers', 'Grey Pleated Drawstring Trousers', 'Relaxed grey trousers combining wide proportions with pleated construction and a drawstring waist. Designed around a loose, oversized silhouette.', 'bottoms', 'bottoms.trousers', 289900, 'Grey', '#46454c', array['Front pleats', 'Drawstring waist', 'Wide leg', 'Side pockets']::text[], false, 'active', 'prototype', 'P3-4', null, null, null, '{"imageRights":"unconfirmed","thirdPartyMarks":true,"personVisible":true,"otherItemsInFrame":true}'::jsonb) on conflict (id) do nothing;
insert into public.products (id, sku, slug, name, description, category_id, subcategory_id, price_paise, colour_label, colour_swatch, features, is_featured, status, data_status, catalogue_ref, material, care, origin, review) values ('ky-proto-011', 'KTS-TOP-006', 'flame-print-washed-zip-hoodie', 'Flame Print Washed Zip Hoodie', 'A charcoal-washed zip hoodie featuring contrasting flame graphics along the sleeves. The oversized streetwear profile makes it suitable as a statement outer layer.', 'tops', 'tops.hoodies', 349900, 'Charcoal / Magenta / Cream', '#363736', array['Washed finish', 'Full zip', 'Hood', 'Flame print on sleeves', 'Kangaroo pockets']::text[], false, 'active', 'prototype', 'P3-5', null, null, null, '{"imageRights":"unconfirmed","thirdPartyMarks":true,"personVisible":true,"otherItemsInFrame":true}'::jsonb) on conflict (id) do nothing;
insert into public.products (id, sku, slug, name, description, category_id, subcategory_id, price_paise, colour_label, colour_swatch, features, is_featured, status, data_status, catalogue_ref, material, care, origin, review) values ('ky-proto-012', 'KTS-BTM-006', 'flame-edge-wide-joggers', 'Flame Edge Wide Joggers', 'Wide charcoal-wash joggers featuring contrasting flame artwork near the lower leg. Designed to pair visually with oversized streetwear tops and hoodies.', 'bottoms', 'bottoms.trousers', 299900, 'Charcoal / Magenta / Cream', '#312f31', array['Washed finish', 'Elasticated waist', 'Flame print at hem', 'Wide leg']::text[], false, 'active', 'prototype', 'P3-6', null, null, null, '{"imageRights":"unconfirmed","thirdPartyMarks":true,"personVisible":true,"otherItemsInFrame":true}'::jsonb) on conflict (id) do nothing;
insert into public.products (id, sku, slug, name, description, category_id, subcategory_id, price_paise, colour_label, colour_swatch, features, is_featured, status, data_status, catalogue_ref, material, care, origin, review) values ('ky-proto-013', 'KTS-TOP-007', 'red-plaid-layered-graphic-top', 'Red Plaid Layered Graphic Top', 'A layered statement top combining a black base with a red graphic lace-up panel, red plaid sleeves and a mesh layer for a multi-texture streetwear look.', 'tops', 'tops.tops', 269900, 'Black / Red / Grey', '#1f1c22', array['Layered construction', 'Lace-up graphic panel', 'Plaid sleeves', 'Mesh underlayer', 'Raw edges']::text[], false, 'active', 'prototype', 'P3-7', null, null, null, '{"imageRights":"unconfirmed","thirdPartyMarks":true,"personVisible":true,"otherItemsInFrame":true}'::jsonb) on conflict (id) do nothing;
insert into public.products (id, sku, slug, name, description, category_id, subcategory_id, price_paise, colour_label, colour_swatch, features, is_featured, status, data_status, catalogue_ref, material, care, origin, review) values ('ky-proto-014', 'KTS-BTM-007', 'red-star-wide-utility-shorts', 'Red Star Wide Utility Shorts', 'Relaxed wide shorts featuring a contrasting red star panel, vertical black-and-white stripes and a drawstring waist.', 'bottoms', 'bottoms.shorts-skirts', 239900, 'Light Grey / Red / Black', '#9e9d97', array['Star appliqué panel', 'Side stripes', 'Drawstring waist', 'Below-knee length']::text[], false, 'active', 'prototype', 'P3-8', null, null, null, '{"imageRights":"unconfirmed","thirdPartyMarks":true,"personVisible":true,"otherItemsInFrame":true}'::jsonb) on conflict (id) do nothing;
insert into public.products (id, sku, slug, name, description, category_id, subcategory_id, price_paise, colour_label, colour_swatch, features, is_featured, status, data_status, catalogue_ref, material, care, origin, review) values ('ky-proto-015', 'KTS-OUT-001', 'hook-closure-cropped-jacket', 'Hook Closure Cropped Jacket', 'A cropped dark jacket with a structured stand collar, metal hook-style closures and a chest pocket detail. Designed around a compact, industrial-inspired silhouette.', 'outerwear', 'outerwear.jackets', 379900, 'Black / Charcoal', '#343434', array['Stand collar with zip', 'Asymmetric metal hook closures', 'Chest pocket', 'Elasticated hem and cuffs']::text[], true, 'active', 'prototype', 'P4-1', null, null, null, '{"imageRights":"unconfirmed","thirdPartyMarks":true,"personVisible":false,"otherItemsInFrame":false}'::jsonb) on conflict (id) do nothing;
insert into public.products (id, sku, slug, name, description, category_id, subcategory_id, price_paise, colour_label, colour_swatch, features, is_featured, status, data_status, catalogue_ref, material, care, origin, review) values ('ky-proto-016', 'KTS-OUT-002', 'faded-navy-stand-collar-jacket', 'Faded Navy Stand-Collar Jacket', 'A faded navy-and-black zip jacket featuring a stand collar, metal hook closures and a small chest detail. Its washed appearance gives it a worn-in streetwear aesthetic.', 'outerwear', 'outerwear.jackets', 379900, 'Navy / Black', '#261e22', array['Faded finish', 'High stand collar', 'Two-way zip', 'Metal hook closures', 'Chest badge']::text[], true, 'active', 'prototype', 'P4-2', null, null, null, '{"imageRights":"unconfirmed","thirdPartyMarks":true,"personVisible":false,"otherItemsInFrame":false}'::jsonb) on conflict (id) do nothing;
insert into public.products (id, sku, slug, name, description, category_id, subcategory_id, price_paise, colour_label, colour_swatch, features, is_featured, status, data_status, catalogue_ref, material, care, origin, review) values ('ky-proto-017', 'KTS-BTM-008', 'olive-balloon-utility-trousers', 'Olive Balloon Utility Trousers', 'Oversized olive-green trousers with a balloon-leg silhouette and adjustable drawstring detailing. Built visually around volume and relaxed proportions.', 'bottoms', 'bottoms.trousers', 299900, 'Olive Green', '#464933', array['Toggle drawstring waist', 'Balloon leg', 'Gathered ankle', 'Side pockets']::text[], true, 'active', 'prototype', 'P4-3', null, null, null, '{"imageRights":"unconfirmed","thirdPartyMarks":false,"personVisible":true,"otherItemsInFrame":true}'::jsonb) on conflict (id) do nothing;
insert into public.products (id, sku, slug, name, description, category_id, subcategory_id, price_paise, colour_label, colour_swatch, features, is_featured, status, data_status, catalogue_ref, material, care, origin, review) values ('ky-proto-018', 'KTS-TOP-008', 'navy-side-tie-boxy-top', 'Navy Side-Tie Boxy Top', 'A sleeveless boxy top in deep navy and black featuring side-tie details. Its simple construction works as a foundation piece for layered styling.', 'tops', 'tops.tops', 219900, 'Navy / Black', '#1b1b21', array['Boxy cut', 'Extended shoulders', 'Side ties', 'Split hem']::text[], false, 'active', 'prototype', 'P4-4', null, null, null, '{"imageRights":"unconfirmed","thirdPartyMarks":true,"personVisible":false,"otherItemsInFrame":false}'::jsonb) on conflict (id) do nothing;
insert into public.products (id, sku, slug, name, description, category_id, subcategory_id, price_paise, colour_label, colour_swatch, features, is_featured, status, data_status, catalogue_ref, material, care, origin, review) values ('ky-proto-019', 'KTS-TOP-009', 'oversized-white-shirt', 'Oversized White Shirt', 'A clean oversized white shirt designed around a relaxed silhouette. Its minimal appearance allows it to work as a standalone piece or as a layering base.', 'tops', 'tops.shirts', 249900, 'White', '#e4e3e8', array['Dropped shoulder', 'Curved hem', 'Button cuffs', 'Point collar']::text[], false, 'active', 'prototype', 'P4-5', null, null, null, '{"imageRights":"unconfirmed","thirdPartyMarks":true,"personVisible":false,"otherItemsInFrame":false}'::jsonb) on conflict (id) do nothing;
insert into public.products (id, sku, slug, name, description, category_id, subcategory_id, price_paise, colour_label, colour_swatch, features, is_featured, status, data_status, catalogue_ref, material, care, origin, review) values ('ky-proto-020', 'KTS-BTM-009', 'check-sash-balloon-trousers', 'Check Sash Balloon Trousers', 'Black balloon trousers featuring a contrasting black-and-white checked sash detail. The exaggerated silhouette gives the piece a strong editorial streetwear profile.', 'bottoms', 'bottoms.trousers', 299900, 'Black / White', '#0d0d14', array['Balloon leg', 'Check sash tie', 'Gathered ankle']::text[], false, 'active', 'prototype', 'P4-6', null, null, null, '{"imageRights":"unconfirmed","thirdPartyMarks":false,"personVisible":false,"otherItemsInFrame":true}'::jsonb) on conflict (id) do nothing;
insert into public.products (id, sku, slug, name, description, category_id, subcategory_id, price_paise, colour_label, colour_swatch, features, is_featured, status, data_status, catalogue_ref, material, care, origin, review) values ('ky-proto-021', 'KTS-TOP-010', 'striped-frog-button-layered-shirt', 'Striped Frog-Button Layered Shirt', 'A cropped blue-and-white striped shirt featuring distinctive knotted frog-style buttons and layered styling over a white long-sleeve base.', 'tops', 'tops.shirts', 269900, 'Blue / White', '#9c99a0', array['Stripe', 'Asymmetric knotted-button closure', 'Cropped length', 'Short sleeves']::text[], false, 'active', 'prototype', 'P4-7', null, null, null, '{"imageRights":"unconfirmed","thirdPartyMarks":false,"personVisible":true,"otherItemsInFrame":true}'::jsonb) on conflict (id) do nothing;
insert into public.products (id, sku, slug, name, description, category_id, subcategory_id, price_paise, colour_label, colour_swatch, features, is_featured, status, data_status, catalogue_ref, material, care, origin, review) values ('ky-proto-022', 'KTS-BTM-010', 'dark-denim-pleated-balloon-trousers', 'Dark Denim Pleated Balloon Trousers', 'Dark denim trousers combining pleated construction with an oversized balloon silhouette. Designed as a statement bottom with a structured yet relaxed appearance.', 'bottoms', 'bottoms.jeans', 319900, 'Dark Denim', '#1b1a1f', array['Dark denim', 'Front pleats', 'Balloon leg', 'Side pockets']::text[], false, 'active', 'prototype', 'P4-8', null, null, null, '{"imageRights":"unconfirmed","thirdPartyMarks":false,"personVisible":true,"otherItemsInFrame":true}'::jsonb) on conflict (id) do nothing;

-- size variants: 10 units of PROTOTYPE stock per size, plus a 'seed' inventory movement for each new variant
with new_variants as (
  insert into public.product_variants (product_id, size, sku, sort_order, stock_qty, stock_source, is_active) values
    ('ky-proto-001', 'XS', 'KTS-TOP-001-XS', 0, 10, 'prototype', true),
    ('ky-proto-001', 'S', 'KTS-TOP-001-S', 1, 10, 'prototype', true),
    ('ky-proto-001', 'M', 'KTS-TOP-001-M', 2, 10, 'prototype', true),
    ('ky-proto-001', 'L', 'KTS-TOP-001-L', 3, 10, 'prototype', true),
    ('ky-proto-001', 'XL', 'KTS-TOP-001-XL', 4, 10, 'prototype', true)
  on conflict (product_id, size) do nothing
  returning id, stock_qty
) insert into public.inventory_movements (variant_id, delta, reason, note)
  select id, stock_qty, 'seed', 'Prototype demo stock' from new_variants;
with new_variants as (
  insert into public.product_variants (product_id, size, sku, sort_order, stock_qty, stock_source, is_active) values
    ('ky-proto-002', 'XS', 'KTS-BTM-001-XS', 0, 10, 'prototype', true),
    ('ky-proto-002', 'S', 'KTS-BTM-001-S', 1, 10, 'prototype', true),
    ('ky-proto-002', 'M', 'KTS-BTM-001-M', 2, 10, 'prototype', true),
    ('ky-proto-002', 'L', 'KTS-BTM-001-L', 3, 10, 'prototype', true),
    ('ky-proto-002', 'XL', 'KTS-BTM-001-XL', 4, 10, 'prototype', true)
  on conflict (product_id, size) do nothing
  returning id, stock_qty
) insert into public.inventory_movements (variant_id, delta, reason, note)
  select id, stock_qty, 'seed', 'Prototype demo stock' from new_variants;
with new_variants as (
  insert into public.product_variants (product_id, size, sku, sort_order, stock_qty, stock_source, is_active) values
    ('ky-proto-003', 'XS', 'KTS-TOP-002-XS', 0, 10, 'prototype', true),
    ('ky-proto-003', 'S', 'KTS-TOP-002-S', 1, 10, 'prototype', true),
    ('ky-proto-003', 'M', 'KTS-TOP-002-M', 2, 10, 'prototype', true),
    ('ky-proto-003', 'L', 'KTS-TOP-002-L', 3, 10, 'prototype', true),
    ('ky-proto-003', 'XL', 'KTS-TOP-002-XL', 4, 10, 'prototype', true)
  on conflict (product_id, size) do nothing
  returning id, stock_qty
) insert into public.inventory_movements (variant_id, delta, reason, note)
  select id, stock_qty, 'seed', 'Prototype demo stock' from new_variants;
with new_variants as (
  insert into public.product_variants (product_id, size, sku, sort_order, stock_qty, stock_source, is_active) values
    ('ky-proto-004', 'XS', 'KTS-BTM-002-XS', 0, 10, 'prototype', true),
    ('ky-proto-004', 'S', 'KTS-BTM-002-S', 1, 10, 'prototype', true),
    ('ky-proto-004', 'M', 'KTS-BTM-002-M', 2, 10, 'prototype', true),
    ('ky-proto-004', 'L', 'KTS-BTM-002-L', 3, 10, 'prototype', true),
    ('ky-proto-004', 'XL', 'KTS-BTM-002-XL', 4, 10, 'prototype', true)
  on conflict (product_id, size) do nothing
  returning id, stock_qty
) insert into public.inventory_movements (variant_id, delta, reason, note)
  select id, stock_qty, 'seed', 'Prototype demo stock' from new_variants;
with new_variants as (
  insert into public.product_variants (product_id, size, sku, sort_order, stock_qty, stock_source, is_active) values
    ('ky-proto-005', 'XS', 'KTS-TOP-003-XS', 0, 10, 'prototype', true),
    ('ky-proto-005', 'S', 'KTS-TOP-003-S', 1, 10, 'prototype', true),
    ('ky-proto-005', 'M', 'KTS-TOP-003-M', 2, 10, 'prototype', true),
    ('ky-proto-005', 'L', 'KTS-TOP-003-L', 3, 10, 'prototype', true),
    ('ky-proto-005', 'XL', 'KTS-TOP-003-XL', 4, 10, 'prototype', true)
  on conflict (product_id, size) do nothing
  returning id, stock_qty
) insert into public.inventory_movements (variant_id, delta, reason, note)
  select id, stock_qty, 'seed', 'Prototype demo stock' from new_variants;
with new_variants as (
  insert into public.product_variants (product_id, size, sku, sort_order, stock_qty, stock_source, is_active) values
    ('ky-proto-006', 'XS', 'KTS-BTM-003-XS', 0, 10, 'prototype', true),
    ('ky-proto-006', 'S', 'KTS-BTM-003-S', 1, 10, 'prototype', true),
    ('ky-proto-006', 'M', 'KTS-BTM-003-M', 2, 10, 'prototype', true),
    ('ky-proto-006', 'L', 'KTS-BTM-003-L', 3, 10, 'prototype', true),
    ('ky-proto-006', 'XL', 'KTS-BTM-003-XL', 4, 10, 'prototype', true)
  on conflict (product_id, size) do nothing
  returning id, stock_qty
) insert into public.inventory_movements (variant_id, delta, reason, note)
  select id, stock_qty, 'seed', 'Prototype demo stock' from new_variants;
with new_variants as (
  insert into public.product_variants (product_id, size, sku, sort_order, stock_qty, stock_source, is_active) values
    ('ky-proto-007', 'XS', 'KTS-TOP-004-XS', 0, 10, 'prototype', true),
    ('ky-proto-007', 'S', 'KTS-TOP-004-S', 1, 10, 'prototype', true),
    ('ky-proto-007', 'M', 'KTS-TOP-004-M', 2, 10, 'prototype', true),
    ('ky-proto-007', 'L', 'KTS-TOP-004-L', 3, 10, 'prototype', true),
    ('ky-proto-007', 'XL', 'KTS-TOP-004-XL', 4, 10, 'prototype', true)
  on conflict (product_id, size) do nothing
  returning id, stock_qty
) insert into public.inventory_movements (variant_id, delta, reason, note)
  select id, stock_qty, 'seed', 'Prototype demo stock' from new_variants;
with new_variants as (
  insert into public.product_variants (product_id, size, sku, sort_order, stock_qty, stock_source, is_active) values
    ('ky-proto-008', '28', 'KTS-BTM-004-28', 0, 10, 'prototype', true),
    ('ky-proto-008', '30', 'KTS-BTM-004-30', 1, 10, 'prototype', true),
    ('ky-proto-008', '32', 'KTS-BTM-004-32', 2, 10, 'prototype', true),
    ('ky-proto-008', '34', 'KTS-BTM-004-34', 3, 10, 'prototype', true),
    ('ky-proto-008', '36', 'KTS-BTM-004-36', 4, 10, 'prototype', true)
  on conflict (product_id, size) do nothing
  returning id, stock_qty
) insert into public.inventory_movements (variant_id, delta, reason, note)
  select id, stock_qty, 'seed', 'Prototype demo stock' from new_variants;
with new_variants as (
  insert into public.product_variants (product_id, size, sku, sort_order, stock_qty, stock_source, is_active) values
    ('ky-proto-009', 'XS', 'KTS-TOP-005-XS', 0, 10, 'prototype', true),
    ('ky-proto-009', 'S', 'KTS-TOP-005-S', 1, 10, 'prototype', true),
    ('ky-proto-009', 'M', 'KTS-TOP-005-M', 2, 10, 'prototype', true),
    ('ky-proto-009', 'L', 'KTS-TOP-005-L', 3, 10, 'prototype', true),
    ('ky-proto-009', 'XL', 'KTS-TOP-005-XL', 4, 10, 'prototype', true)
  on conflict (product_id, size) do nothing
  returning id, stock_qty
) insert into public.inventory_movements (variant_id, delta, reason, note)
  select id, stock_qty, 'seed', 'Prototype demo stock' from new_variants;
with new_variants as (
  insert into public.product_variants (product_id, size, sku, sort_order, stock_qty, stock_source, is_active) values
    ('ky-proto-010', 'XS', 'KTS-BTM-005-XS', 0, 10, 'prototype', true),
    ('ky-proto-010', 'S', 'KTS-BTM-005-S', 1, 10, 'prototype', true),
    ('ky-proto-010', 'M', 'KTS-BTM-005-M', 2, 10, 'prototype', true),
    ('ky-proto-010', 'L', 'KTS-BTM-005-L', 3, 10, 'prototype', true),
    ('ky-proto-010', 'XL', 'KTS-BTM-005-XL', 4, 10, 'prototype', true)
  on conflict (product_id, size) do nothing
  returning id, stock_qty
) insert into public.inventory_movements (variant_id, delta, reason, note)
  select id, stock_qty, 'seed', 'Prototype demo stock' from new_variants;
with new_variants as (
  insert into public.product_variants (product_id, size, sku, sort_order, stock_qty, stock_source, is_active) values
    ('ky-proto-011', 'XS', 'KTS-TOP-006-XS', 0, 10, 'prototype', true),
    ('ky-proto-011', 'S', 'KTS-TOP-006-S', 1, 10, 'prototype', true),
    ('ky-proto-011', 'M', 'KTS-TOP-006-M', 2, 10, 'prototype', true),
    ('ky-proto-011', 'L', 'KTS-TOP-006-L', 3, 10, 'prototype', true),
    ('ky-proto-011', 'XL', 'KTS-TOP-006-XL', 4, 10, 'prototype', true)
  on conflict (product_id, size) do nothing
  returning id, stock_qty
) insert into public.inventory_movements (variant_id, delta, reason, note)
  select id, stock_qty, 'seed', 'Prototype demo stock' from new_variants;
with new_variants as (
  insert into public.product_variants (product_id, size, sku, sort_order, stock_qty, stock_source, is_active) values
    ('ky-proto-012', 'XS', 'KTS-BTM-006-XS', 0, 10, 'prototype', true),
    ('ky-proto-012', 'S', 'KTS-BTM-006-S', 1, 10, 'prototype', true),
    ('ky-proto-012', 'M', 'KTS-BTM-006-M', 2, 10, 'prototype', true),
    ('ky-proto-012', 'L', 'KTS-BTM-006-L', 3, 10, 'prototype', true),
    ('ky-proto-012', 'XL', 'KTS-BTM-006-XL', 4, 10, 'prototype', true)
  on conflict (product_id, size) do nothing
  returning id, stock_qty
) insert into public.inventory_movements (variant_id, delta, reason, note)
  select id, stock_qty, 'seed', 'Prototype demo stock' from new_variants;
with new_variants as (
  insert into public.product_variants (product_id, size, sku, sort_order, stock_qty, stock_source, is_active) values
    ('ky-proto-013', 'XS', 'KTS-TOP-007-XS', 0, 10, 'prototype', true),
    ('ky-proto-013', 'S', 'KTS-TOP-007-S', 1, 10, 'prototype', true),
    ('ky-proto-013', 'M', 'KTS-TOP-007-M', 2, 10, 'prototype', true),
    ('ky-proto-013', 'L', 'KTS-TOP-007-L', 3, 10, 'prototype', true),
    ('ky-proto-013', 'XL', 'KTS-TOP-007-XL', 4, 10, 'prototype', true)
  on conflict (product_id, size) do nothing
  returning id, stock_qty
) insert into public.inventory_movements (variant_id, delta, reason, note)
  select id, stock_qty, 'seed', 'Prototype demo stock' from new_variants;
with new_variants as (
  insert into public.product_variants (product_id, size, sku, sort_order, stock_qty, stock_source, is_active) values
    ('ky-proto-014', 'XS', 'KTS-BTM-007-XS', 0, 10, 'prototype', true),
    ('ky-proto-014', 'S', 'KTS-BTM-007-S', 1, 10, 'prototype', true),
    ('ky-proto-014', 'M', 'KTS-BTM-007-M', 2, 10, 'prototype', true),
    ('ky-proto-014', 'L', 'KTS-BTM-007-L', 3, 10, 'prototype', true),
    ('ky-proto-014', 'XL', 'KTS-BTM-007-XL', 4, 10, 'prototype', true)
  on conflict (product_id, size) do nothing
  returning id, stock_qty
) insert into public.inventory_movements (variant_id, delta, reason, note)
  select id, stock_qty, 'seed', 'Prototype demo stock' from new_variants;
with new_variants as (
  insert into public.product_variants (product_id, size, sku, sort_order, stock_qty, stock_source, is_active) values
    ('ky-proto-015', 'XS', 'KTS-OUT-001-XS', 0, 10, 'prototype', true),
    ('ky-proto-015', 'S', 'KTS-OUT-001-S', 1, 10, 'prototype', true),
    ('ky-proto-015', 'M', 'KTS-OUT-001-M', 2, 10, 'prototype', true),
    ('ky-proto-015', 'L', 'KTS-OUT-001-L', 3, 10, 'prototype', true),
    ('ky-proto-015', 'XL', 'KTS-OUT-001-XL', 4, 10, 'prototype', true)
  on conflict (product_id, size) do nothing
  returning id, stock_qty
) insert into public.inventory_movements (variant_id, delta, reason, note)
  select id, stock_qty, 'seed', 'Prototype demo stock' from new_variants;
with new_variants as (
  insert into public.product_variants (product_id, size, sku, sort_order, stock_qty, stock_source, is_active) values
    ('ky-proto-016', 'XS', 'KTS-OUT-002-XS', 0, 10, 'prototype', true),
    ('ky-proto-016', 'S', 'KTS-OUT-002-S', 1, 10, 'prototype', true),
    ('ky-proto-016', 'M', 'KTS-OUT-002-M', 2, 10, 'prototype', true),
    ('ky-proto-016', 'L', 'KTS-OUT-002-L', 3, 10, 'prototype', true),
    ('ky-proto-016', 'XL', 'KTS-OUT-002-XL', 4, 10, 'prototype', true)
  on conflict (product_id, size) do nothing
  returning id, stock_qty
) insert into public.inventory_movements (variant_id, delta, reason, note)
  select id, stock_qty, 'seed', 'Prototype demo stock' from new_variants;
with new_variants as (
  insert into public.product_variants (product_id, size, sku, sort_order, stock_qty, stock_source, is_active) values
    ('ky-proto-017', 'XS', 'KTS-BTM-008-XS', 0, 10, 'prototype', true),
    ('ky-proto-017', 'S', 'KTS-BTM-008-S', 1, 10, 'prototype', true),
    ('ky-proto-017', 'M', 'KTS-BTM-008-M', 2, 10, 'prototype', true),
    ('ky-proto-017', 'L', 'KTS-BTM-008-L', 3, 10, 'prototype', true),
    ('ky-proto-017', 'XL', 'KTS-BTM-008-XL', 4, 10, 'prototype', true)
  on conflict (product_id, size) do nothing
  returning id, stock_qty
) insert into public.inventory_movements (variant_id, delta, reason, note)
  select id, stock_qty, 'seed', 'Prototype demo stock' from new_variants;
with new_variants as (
  insert into public.product_variants (product_id, size, sku, sort_order, stock_qty, stock_source, is_active) values
    ('ky-proto-018', 'XS', 'KTS-TOP-008-XS', 0, 10, 'prototype', true),
    ('ky-proto-018', 'S', 'KTS-TOP-008-S', 1, 10, 'prototype', true),
    ('ky-proto-018', 'M', 'KTS-TOP-008-M', 2, 10, 'prototype', true),
    ('ky-proto-018', 'L', 'KTS-TOP-008-L', 3, 10, 'prototype', true),
    ('ky-proto-018', 'XL', 'KTS-TOP-008-XL', 4, 10, 'prototype', true)
  on conflict (product_id, size) do nothing
  returning id, stock_qty
) insert into public.inventory_movements (variant_id, delta, reason, note)
  select id, stock_qty, 'seed', 'Prototype demo stock' from new_variants;
with new_variants as (
  insert into public.product_variants (product_id, size, sku, sort_order, stock_qty, stock_source, is_active) values
    ('ky-proto-019', 'XS', 'KTS-TOP-009-XS', 0, 10, 'prototype', true),
    ('ky-proto-019', 'S', 'KTS-TOP-009-S', 1, 10, 'prototype', true),
    ('ky-proto-019', 'M', 'KTS-TOP-009-M', 2, 10, 'prototype', true),
    ('ky-proto-019', 'L', 'KTS-TOP-009-L', 3, 10, 'prototype', true),
    ('ky-proto-019', 'XL', 'KTS-TOP-009-XL', 4, 10, 'prototype', true)
  on conflict (product_id, size) do nothing
  returning id, stock_qty
) insert into public.inventory_movements (variant_id, delta, reason, note)
  select id, stock_qty, 'seed', 'Prototype demo stock' from new_variants;
with new_variants as (
  insert into public.product_variants (product_id, size, sku, sort_order, stock_qty, stock_source, is_active) values
    ('ky-proto-020', 'XS', 'KTS-BTM-009-XS', 0, 10, 'prototype', true),
    ('ky-proto-020', 'S', 'KTS-BTM-009-S', 1, 10, 'prototype', true),
    ('ky-proto-020', 'M', 'KTS-BTM-009-M', 2, 10, 'prototype', true),
    ('ky-proto-020', 'L', 'KTS-BTM-009-L', 3, 10, 'prototype', true),
    ('ky-proto-020', 'XL', 'KTS-BTM-009-XL', 4, 10, 'prototype', true)
  on conflict (product_id, size) do nothing
  returning id, stock_qty
) insert into public.inventory_movements (variant_id, delta, reason, note)
  select id, stock_qty, 'seed', 'Prototype demo stock' from new_variants;
with new_variants as (
  insert into public.product_variants (product_id, size, sku, sort_order, stock_qty, stock_source, is_active) values
    ('ky-proto-021', 'XS', 'KTS-TOP-010-XS', 0, 10, 'prototype', true),
    ('ky-proto-021', 'S', 'KTS-TOP-010-S', 1, 10, 'prototype', true),
    ('ky-proto-021', 'M', 'KTS-TOP-010-M', 2, 10, 'prototype', true),
    ('ky-proto-021', 'L', 'KTS-TOP-010-L', 3, 10, 'prototype', true),
    ('ky-proto-021', 'XL', 'KTS-TOP-010-XL', 4, 10, 'prototype', true)
  on conflict (product_id, size) do nothing
  returning id, stock_qty
) insert into public.inventory_movements (variant_id, delta, reason, note)
  select id, stock_qty, 'seed', 'Prototype demo stock' from new_variants;
with new_variants as (
  insert into public.product_variants (product_id, size, sku, sort_order, stock_qty, stock_source, is_active) values
    ('ky-proto-022', 'XS', 'KTS-BTM-010-XS', 0, 10, 'prototype', true),
    ('ky-proto-022', 'S', 'KTS-BTM-010-S', 1, 10, 'prototype', true),
    ('ky-proto-022', 'M', 'KTS-BTM-010-M', 2, 10, 'prototype', true),
    ('ky-proto-022', 'L', 'KTS-BTM-010-L', 3, 10, 'prototype', true),
    ('ky-proto-022', 'XL', 'KTS-BTM-010-XL', 4, 10, 'prototype', true)
  on conflict (product_id, size) do nothing
  returning id, stock_qty
) insert into public.inventory_movements (variant_id, delta, reason, note)
  select id, stock_qty, 'seed', 'Prototype demo stock' from new_variants;

-- primary images (files are uploaded to the product-images bucket by scripts/upload-images.mjs)
insert into public.product_images (product_id, storage_path, width, height, alt, quality, zoom, is_primary, sort_order) values ('ky-proto-001', 'products/ky-proto-001.webp', 370, 526, 'Asymmetric Zip Collar Top, Taupe / Grey', 'prototype', false, true, 0) on conflict (product_id, storage_path) do nothing;
insert into public.product_images (product_id, storage_path, width, height, alt, quality, zoom, is_primary, sort_order) values ('ky-proto-002', 'products/ky-proto-002.webp', 343, 766, 'Draped Utility Wide Trousers, Khaki / Taupe', 'prototype', false, true, 0) on conflict (product_id, storage_path) do nothing;
insert into public.product_images (product_id, storage_path, width, height, alt, quality, zoom, is_primary, sort_order) values ('ky-proto-003', 'products/ky-proto-003.webp', 489, 593, 'Washed Lace-Up Pointed Shirt, Washed Blue / Grey', 'prototype', false, true, 0) on conflict (product_id, storage_path) do nothing;
insert into public.product_images (product_id, storage_path, width, height, alt, quality, zoom, is_primary, sort_order) values ('ky-proto-004', 'products/ky-proto-004.webp', 525, 371, 'Check Buckle Mini Skirt, Light Blue / Red', 'prototype', false, true, 0) on conflict (product_id, storage_path) do nothing;
insert into public.product_images (product_id, storage_path, width, height, alt, quality, zoom, is_primary, sort_order) values ('ky-proto-005', 'products/ky-proto-005.webp', 440, 616, 'Sheer Floral Lace-Up Top, Off White', 'prototype', false, true, 0) on conflict (product_id, storage_path) do nothing;
insert into public.product_images (product_id, storage_path, width, height, alt, quality, zoom, is_primary, sort_order) values ('ky-proto-006', 'products/ky-proto-006.webp', 274, 575, 'Charcoal Pleated Balloon Trousers, Charcoal / Black', 'prototype', false, true, 0) on conflict (product_id, storage_path) do nothing;
insert into public.product_images (product_id, storage_path, width, height, alt, quality, zoom, is_primary, sort_order) values ('ky-proto-007', 'products/ky-proto-007.webp', 409, 693, 'Acid Wash Gothic Hooded Top, Grey / Acid Wash', 'prototype', false, true, 0) on conflict (product_id, storage_path) do nothing;
insert into public.product_images (product_id, storage_path, width, height, alt, quality, zoom, is_primary, sort_order) values ('ky-proto-008', 'products/ky-proto-008.webp', 396, 793, 'Faded Black Wide-Leg Jeans, Faded Black', 'prototype', false, true, 0) on conflict (product_id, storage_path) do nothing;
insert into public.product_images (product_id, storage_path, width, height, alt, quality, zoom, is_primary, sort_order) values ('ky-proto-009', 'products/ky-proto-009.webp', 464, 587, 'Layered Pinstripe Waffle Shirt, Black / Light Grey', 'prototype', false, true, 0) on conflict (product_id, storage_path) do nothing;
insert into public.product_images (product_id, storage_path, width, height, alt, quality, zoom, is_primary, sort_order) values ('ky-proto-010', 'products/ky-proto-010.webp', 418, 691, 'Grey Pleated Drawstring Trousers, Grey', 'prototype', false, true, 0) on conflict (product_id, storage_path) do nothing;
insert into public.product_images (product_id, storage_path, width, height, alt, quality, zoom, is_primary, sort_order) values ('ky-proto-011', 'products/ky-proto-011.webp', 432, 562, 'Flame Print Washed Zip Hoodie, Charcoal / Magenta / Cream', 'prototype', false, true, 0) on conflict (product_id, storage_path) do nothing;
insert into public.product_images (product_id, storage_path, width, height, alt, quality, zoom, is_primary, sort_order) values ('ky-proto-012', 'products/ky-proto-012.webp', 394, 602, 'Flame Edge Wide Joggers, Charcoal / Magenta / Cream', 'prototype', false, true, 0) on conflict (product_id, storage_path) do nothing;
insert into public.product_images (product_id, storage_path, width, height, alt, quality, zoom, is_primary, sort_order) values ('ky-proto-013', 'products/ky-proto-013.webp', 444, 600, 'Red Plaid Layered Graphic Top, Black / Red / Grey', 'prototype', false, true, 0) on conflict (product_id, storage_path) do nothing;
insert into public.product_images (product_id, storage_path, width, height, alt, quality, zoom, is_primary, sort_order) values ('ky-proto-014', 'products/ky-proto-014.webp', 368, 753, 'Red Star Wide Utility Shorts, Light Grey / Red / Black', 'prototype', false, true, 0) on conflict (product_id, storage_path) do nothing;
insert into public.product_images (product_id, storage_path, width, height, alt, quality, zoom, is_primary, sort_order) values ('ky-proto-015', 'products/ky-proto-015.webp', 467, 495, 'Hook Closure Cropped Jacket, Black / Charcoal', 'prototype', false, true, 0) on conflict (product_id, storage_path) do nothing;
insert into public.product_images (product_id, storage_path, width, height, alt, quality, zoom, is_primary, sort_order) values ('ky-proto-016', 'products/ky-proto-016.webp', 416, 496, 'Faded Navy Stand-Collar Jacket, Navy / Black', 'prototype', false, true, 0) on conflict (product_id, storage_path) do nothing;
insert into public.product_images (product_id, storage_path, width, height, alt, quality, zoom, is_primary, sort_order) values ('ky-proto-017', 'products/ky-proto-017.webp', 383, 702, 'Olive Balloon Utility Trousers, Olive Green', 'prototype', false, true, 0) on conflict (product_id, storage_path) do nothing;
insert into public.product_images (product_id, storage_path, width, height, alt, quality, zoom, is_primary, sort_order) values ('ky-proto-018', 'products/ky-proto-018.webp', 349, 353, 'Navy Side-Tie Boxy Top, Navy / Black', 'prototype', false, true, 0) on conflict (product_id, storage_path) do nothing;
insert into public.product_images (product_id, storage_path, width, height, alt, quality, zoom, is_primary, sort_order) values ('ky-proto-019', 'products/ky-proto-019.webp', 311, 363, 'Oversized White Shirt, White', 'prototype', false, true, 0) on conflict (product_id, storage_path) do nothing;
insert into public.product_images (product_id, storage_path, width, height, alt, quality, zoom, is_primary, sort_order) values ('ky-proto-020', 'products/ky-proto-020.webp', 299, 568, 'Check Sash Balloon Trousers, Black / White', 'prototype', false, true, 0) on conflict (product_id, storage_path) do nothing;
insert into public.product_images (product_id, storage_path, width, height, alt, quality, zoom, is_primary, sort_order) values ('ky-proto-021', 'products/ky-proto-021.webp', 349, 493, 'Striped Frog-Button Layered Shirt, Blue / White', 'prototype', false, true, 0) on conflict (product_id, storage_path) do nothing;
insert into public.product_images (product_id, storage_path, width, height, alt, quality, zoom, is_primary, sort_order) values ('ky-proto-022', 'products/ky-proto-022.webp', 314, 500, 'Dark Denim Pleated Balloon Trousers, Dark Denim', 'prototype', false, true, 0) on conflict (product_id, storage_path) do nothing;

-- collections (New Arrivals keeps its order)
insert into public.collections (id, label, data_status, note) values ('new-arrivals', 'New Arrivals', 'prototype', 'Prototype selection for UI development (KTS-BTM-008, KTS-OUT-001, KTS-BTM-010, KTS-BTM-002). Estimated, not officially confirmed new arrivals.') on conflict (id) do update set label = excluded.label, data_status = excluded.data_status, note = excluded.note;
insert into public.collection_products (collection_id, product_id, position) values ('new-arrivals', 'ky-proto-017', 1) on conflict (collection_id, product_id) do nothing;
insert into public.collection_products (collection_id, product_id, position) values ('new-arrivals', 'ky-proto-015', 2) on conflict (collection_id, product_id) do nothing;
insert into public.collection_products (collection_id, product_id, position) values ('new-arrivals', 'ky-proto-022', 3) on conflict (collection_id, product_id) do nothing;
insert into public.collection_products (collection_id, product_id, position) values ('new-arrivals', 'ky-proto-004', 4) on conflict (collection_id, product_id) do nothing;

-- styled-with pairings (as paired in the prototype catalogue)
insert into public.product_relations (product_id, related_id, kind, position) values ('ky-proto-001', 'ky-proto-002', 'styled_with', 0) on conflict do nothing;
insert into public.product_relations (product_id, related_id, kind, position) values ('ky-proto-002', 'ky-proto-001', 'styled_with', 0) on conflict do nothing;
insert into public.product_relations (product_id, related_id, kind, position) values ('ky-proto-003', 'ky-proto-004', 'styled_with', 0) on conflict do nothing;
insert into public.product_relations (product_id, related_id, kind, position) values ('ky-proto-004', 'ky-proto-003', 'styled_with', 0) on conflict do nothing;
insert into public.product_relations (product_id, related_id, kind, position) values ('ky-proto-005', 'ky-proto-006', 'styled_with', 0) on conflict do nothing;
insert into public.product_relations (product_id, related_id, kind, position) values ('ky-proto-006', 'ky-proto-005', 'styled_with', 0) on conflict do nothing;
insert into public.product_relations (product_id, related_id, kind, position) values ('ky-proto-007', 'ky-proto-008', 'styled_with', 0) on conflict do nothing;
insert into public.product_relations (product_id, related_id, kind, position) values ('ky-proto-008', 'ky-proto-007', 'styled_with', 0) on conflict do nothing;
insert into public.product_relations (product_id, related_id, kind, position) values ('ky-proto-009', 'ky-proto-010', 'styled_with', 0) on conflict do nothing;
insert into public.product_relations (product_id, related_id, kind, position) values ('ky-proto-010', 'ky-proto-009', 'styled_with', 0) on conflict do nothing;
insert into public.product_relations (product_id, related_id, kind, position) values ('ky-proto-011', 'ky-proto-012', 'styled_with', 0) on conflict do nothing;
insert into public.product_relations (product_id, related_id, kind, position) values ('ky-proto-012', 'ky-proto-011', 'styled_with', 0) on conflict do nothing;
insert into public.product_relations (product_id, related_id, kind, position) values ('ky-proto-013', 'ky-proto-014', 'styled_with', 0) on conflict do nothing;
insert into public.product_relations (product_id, related_id, kind, position) values ('ky-proto-014', 'ky-proto-013', 'styled_with', 0) on conflict do nothing;
insert into public.product_relations (product_id, related_id, kind, position) values ('ky-proto-015', 'ky-proto-017', 'styled_with', 0) on conflict do nothing;
insert into public.product_relations (product_id, related_id, kind, position) values ('ky-proto-016', 'ky-proto-017', 'styled_with', 0) on conflict do nothing;
insert into public.product_relations (product_id, related_id, kind, position) values ('ky-proto-017', 'ky-proto-015', 'styled_with', 0) on conflict do nothing;
insert into public.product_relations (product_id, related_id, kind, position) values ('ky-proto-017', 'ky-proto-016', 'styled_with', 1) on conflict do nothing;
insert into public.product_relations (product_id, related_id, kind, position) values ('ky-proto-018', 'ky-proto-019', 'styled_with', 0) on conflict do nothing;
insert into public.product_relations (product_id, related_id, kind, position) values ('ky-proto-018', 'ky-proto-020', 'styled_with', 1) on conflict do nothing;
insert into public.product_relations (product_id, related_id, kind, position) values ('ky-proto-019', 'ky-proto-018', 'styled_with', 0) on conflict do nothing;
insert into public.product_relations (product_id, related_id, kind, position) values ('ky-proto-019', 'ky-proto-020', 'styled_with', 1) on conflict do nothing;
insert into public.product_relations (product_id, related_id, kind, position) values ('ky-proto-020', 'ky-proto-018', 'styled_with', 0) on conflict do nothing;
insert into public.product_relations (product_id, related_id, kind, position) values ('ky-proto-020', 'ky-proto-019', 'styled_with', 1) on conflict do nothing;
insert into public.product_relations (product_id, related_id, kind, position) values ('ky-proto-021', 'ky-proto-022', 'styled_with', 0) on conflict do nothing;
insert into public.product_relations (product_id, related_id, kind, position) values ('ky-proto-022', 'ky-proto-021', 'styled_with', 0) on conflict do nothing;

commit;
