/* Admin navigation. Each item names the permission it needs; the shell shows only items the signed-in staff member
   holds, and every page checks the same permission on the server (hiding a link is never the protection). */
export interface NavItem { href: string; label: string; permission: string; group: string }

export const NAV: NavItem[] = [
  { href: '/dashboard', label: 'Dashboard', permission: 'dashboard.read', group: 'Overview' },
  { href: '/reports', label: 'Reports', permission: 'reports.read', group: 'Overview' },
  { href: '/notifications', label: 'Notifications', permission: 'dashboard.read', group: 'Overview' },
  { href: '/products', label: 'Products', permission: 'products.read', group: 'Catalogue' },
  { href: '/categories', label: 'Categories', permission: 'categories.read', group: 'Catalogue' },
  { href: '/collections', label: 'Collections', permission: 'categories.read', group: 'Catalogue' },
  { href: '/attributes', label: 'Attributes', permission: 'categories.read', group: 'Catalogue' },
  { href: '/size-charts', label: 'Size charts', permission: 'products.read', group: 'Catalogue' },
  { href: '/inventory', label: 'Inventory', permission: 'inventory.read', group: 'Catalogue' },
  { href: '/stock-counts', label: 'Stock counts', permission: 'inventory.read', group: 'Catalogue' },
  { href: '/locations', label: 'Locations', permission: 'inventory.read', group: 'Catalogue' },
  { href: '/transfers', label: 'Transfers', permission: 'inventory.read', group: 'Catalogue' },
  { href: '/stock-value', label: 'Stock value', permission: 'costs.read', group: 'Catalogue' },
  { href: '/pos', label: 'POS billing', permission: 'pos.access', group: 'Commerce' },
  { href: '/orders', label: 'Orders', permission: 'orders.read', group: 'Commerce' },
  { href: '/drafts', label: 'Draft orders', permission: 'orders.read', group: 'Commerce' },
  { href: '/customers', label: 'Customers', permission: 'customers.read', group: 'Commerce' },
  { href: '/payments', label: 'Payments', permission: 'billing.read', group: 'Commerce' },
  { href: '/reviews', label: 'Reviews', permission: 'reviews.read', group: 'Commerce' },
  { href: '/content', label: 'Store content', permission: 'content.manage', group: 'Commerce' },
  { href: '/pricing', label: 'Pricing & discounts', permission: 'pricing.read', group: 'Commerce' },
  { href: '/shipping', label: 'Shipping', permission: 'shipping.read', group: 'Commerce' },
  { href: '/returns', label: 'Returns & refunds', permission: 'returns.read', group: 'Commerce' },
  { href: '/carts', label: 'Carts & wishlists', permission: 'carts.read', group: 'Commerce' },
  { href: '/marketing', label: 'Marketing', permission: 'marketing.read', group: 'Growth' },
  { href: '/support', label: 'Support', permission: 'support.read', group: 'Growth' },
  { href: '/loyalty', label: 'Loyalty points', permission: 'loyalty.read', group: 'Growth' },
  { href: '/finance', label: 'Finance', permission: 'finance.read', group: 'Finance' },
  { href: '/vendors', label: 'Vendors', permission: 'procurement.read', group: 'Supply' },
  { href: '/materials', label: 'Materials', permission: 'procurement.read', group: 'Supply' },
  { href: '/purchase-orders', label: 'Purchase orders', permission: 'procurement.read', group: 'Supply' },
  { href: '/production', label: 'Production', permission: 'production.read', group: 'Supply' },
  { href: '/staff', label: 'Staff', permission: 'staff.read', group: 'System' },
  { href: '/roles', label: 'Roles', permission: 'roles.read', group: 'System' },
  { href: '/audit', label: 'Audit', permission: 'audit.read', group: 'System' },
  { href: '/settings', label: 'Configuration', permission: 'settings.read', group: 'System' },
  { href: '/system', label: 'System', permission: 'system.read', group: 'System' },
];
